### ISSUE TITLE
build warning

### ISSUE THREAD

**Issue by urherenow** [derrekr/ctr_firm_builder#1]
Haven't used this yet, but this warning comes up when building from ubuntu bash:

firm_builder.c: In function ‘main’:
firm_builder.c:189:35: warning: format ‘%x’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char *’ [-Wformat=]
   if (sscanf(section_type_string, "%x", &section_type) != 1)

**Comment by derrekr** [comment]
Hi!
Thanks for reporting this issue. The latest commit should have solved it.

**Comment by Moire9** [comment]
This solved it for me.

**Comment by urherenow** [comment]
Thanks! My apologies for not noticing for so long. I'm on a deployment...
